use_frameworks!

platform :ios, '13.0'

target 'WepinLogin_Example' do
  # pod 'WepinCommon', :path => '../../WepinCommon'
  # pod 'WepinStorage', :path => '../../WepinStorage'
  # pod 'WepinNetwork', :path => '../../WepinNetwork'
  # pod 'WepinSession', :path => '../../WepinSession'
  # pod 'WepinLogin', :path => '../'
  pod 'WepinCommon', '~> 1.1.0'
  pod 'WepinStorage', '~> 1.1.0'
  pod 'WepinNetwork', '~> 1.1.0'
  pod 'WepinSession', '~> 1.1.0'
  pod 'WepinLogin', :'~> 1.1.0'
  target 'WepinLogin_Tests' do
    inherit! :search_paths

  end
end
