use_frameworks!

platform :ios, '13.0'

target 'WepinLogin_Example' do
  # pod 'WepinCommon', :path => '../../WepinCommon'
  # pod 'WepinCore', :path => '../../WepinCore'
  # pod 'WepinLogin', :path => '../'
  pod 'WepinCommon', '~> 1.2.1'
  pod 'WepinCore', '~> 1.2.1'
  pod 'WepinLogin','~> 1.2.1'
  target 'WepinLogin_Tests' do
    inherit! :search_paths

  end
end
